apiVersion: v1
kind: Service
metadata:
  name: pod1-service
  labels:
    app: test-pods
spec:
  selector:
    app: test-pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
