apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: test-pods
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: test-pods
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80

